GET http://localhost:3000/user-api/users
###

POST http://localhost:3000/user-api/user
Content-Type: application/json

{
    "username":"divya",
    "email":"div@gamil.com",
    "mobile":90909090909,
    "cash": 12222
}